name: CI

on:
  push:
    branches: [ main, modernization/phase1 ]
  pull_request:
    branches: [ main, modernization/phase1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip and wheel
        run: python -m pip install --upgrade pip wheel
      - name: Install dependencies (dev)
        run: pip install -e .[dev]
      - name: Lint (black)
        run: black --check src tests
      - name: Lint (isort)
        run: isort --check src tests
      - name: Lint (flake8)
        run: flake8 src tests
      - name: Type check (mypy)
        run: mypy src
      - name: Security check (bandit)
        run: bandit -r src
      - name: Run tests
        run: pytest --cov=src --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
