name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install virutalenv
      run: sudo apt update && sudo apt upgrade && sudo apt install -y python3-virtualenv && sudo apt install -y black && sudo apt install -y flake8

    - name: Install dependencies
      run: make install
      
    - name: Format
      run: make format 
      
    - name: Lint
      run: make lint
  
    - name: Run
      run: make run
      
